image: sogolsahebi/nextflow-r-env:latest

tasks:
  - name: Install Nextflow
    command: |
      curl -s https://get.nextflow.io | bash
      mkdir -p ~/bin
      mv nextflow ~/bin/
      echo "export PATH=\"$HOME/bin:\$PATH\"" >> ~/.bashrc

ports:
  - port: 8888
    onOpen: open-preview
