image: sogolsahebi/nextflow-r-env:latest

tasks:
  - name: Install Nextflow
    command: |
      mkdir -p ~/bin
      if [ ! -f ~/bin/nextflow ]; then
        curl -s https://get.nextflow.io | bash
        mv nextflow ~/bin/
      fi
      if ! grep -Fxq 'export PATH="$HOME/bin:$PATH"' ~/.bashrc; then
        echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      fi
      source ~/.bashrc

ports:
  - port: 8888
    onOpen: open-preview
