image: sogolsahebi/nextflow-r-env:latest

tasks:
  - name: Install Nextflow
    command: |
      if [ ! -f ~/bin/nextflow ]; then
        curl -s https://get.nextflow.io | bash
        mkdir -p ~/bin
        mv nextflow ~/bin/
      fi
      echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc

ports:
  - port: 8888
    onOpen: open-preview
