name: my_r_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - r-base=4.1
  - r-survcomp
  - r-gsva
  - r-dplyr
  - r-meta
  - r-metafor
  - r-forestplot
  - r-ggplot2
  - r-ggrepel
  - r-gridextra
  - r-data.table
  - r-kableextra
  - r-summarytools
  - r-multiassayexperiment
