name: Docker Workflow
on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sogolsahebi
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t sogolsahebi/nextflow-r-env .

      - name: Push Docker Image to Docker Hub
        run: docker push sogolsahebi/nextflow-r-env

      - name: Run commands in Docker container
        run: docker run sogolsahebi/nextflow-r-env <command>

